debug = false
library_path = "$HOME/Music"
metadata_db_path = "$HOME/Music/metadata.db"

# COMMANDS

[commands.add]
auto_tag = true
auto_rename = false
file_action = "copy"  # | "move" | "None"
strategy = "prompt"   # | "overwrite" | "keep"
write_metadata = true

[commands.sync]
strategy = "prompt" # | "prefer-db" | "prefer-files"

# [metadata.template]
# track.title = "{title}{feat_string:safe}"

# RENAMER

[renamer]
template = "{release.artist}/{release.title} ({release.year}) [{release.format} - {release.bit_depth} - {release.sample_rate}]/{number}. {title}"
